=== iFlowBPM/iFlow/iflow-api/src/main/resources/processdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  simple vars come first.. list vars come last -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.iflow.pt/ProcessData" xmlns="http://www.iflow.pt/ProcessData"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xsd:annotation><xsd:documentation>Serialized process representation</xsd:documentation></xsd:annotation>

	<xsd:complexType name="appvar">
		<xsd:annotation><xsd:documentation>Internal application data</xsd:documentation></xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="n" type="xsd:string" use="required">
					<xsd:annotation><xsd:documentation>Variable name</xsd:documentation></xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="simplevar">
		<xsd:annotation><xsd:documentation>Simple variable value data</xsd:documentation></xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="n" type="xsd:string" use="required">
					<xsd:annotation><xsd:documentation>Variable name</xsd:documentation></xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="listvar">
		<xsd:annotation><xsd:documentation>List variable data</xsd:documentation></xsd:annotation>
		<xsd:sequence>
			<xsd:element name="i" type="listitem" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation><xsd:documentation>List items</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="n" type="xsd:string" use="required">
			<xsd:annotation><xsd:documentation>List variable name</xsd:documentation></xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="s" type="xsd:nonNegativeInteger" use="required">
			<xsd:annotation><xsd:documentation>List size (length)</xsd:documentation></xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="listitem">
		<xsd:annotation><xsd:documentation>List item value data</xsd:documentation></xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="p" type="xsd:nonNegativeInteger" use="required">
				<xsd:annotation><xsd:documentation>List element position</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:element name="processdata">
    	<xsd:annotation><xsd:documentation>A process</xsd:documentation></xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="e" type="xsd:string" minOccurs="0" maxOccurs="1">
					<xsd:annotation><xsd:documentation>Current error message</xsd:documentation></xsd:annotation>
				</xsd:element>
				<xsd:element name="d" type="appvar" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation><xsd:documentation>Application data</xsd:documentation></xsd:annotation>
				</xsd:element>
				<xsd:element name="a" type="simplevar" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation><xsd:documentation>Simple variables</xsd:documentation></xsd:annotation>
				</xsd:element>
				<xsd:element name="l" type="listvar" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation><xsd:documentation>List variables</xsd:documentation></xsd:annotation>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="fid" type="xsd:positiveInteger" use="required">
				<xsd:annotation><xsd:documentation>Process flow ID</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="pid" type="xsd:positiveInteger" use="required">
				<xsd:annotation><xsd:documentation>Process ID</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="spid" type="xsd:positiveInteger" use="required">
				<xsd:annotation><xsd:documentation>Subprocess ID (fork id)</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="pnumber" type="xsd:string" use="required">
				<xsd:annotation><xsd:documentation>Process Number (serial number)</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="creator" type="xsd:string" use="required">
				<xsd:annotation><xsd:documentation>Process Creator (user Id)</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="creationDate" type="xsd:dateTime" use="required">
				<xsd:annotation><xsd:documentation>Process creation timestamp</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="currentUser" type="xsd:string" use="required">
				<xsd:annotation><xsd:documentation>User(s) holding the process</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="lastUpdate" type="xsd:dateTime" use="required">
				<xsd:annotation><xsd:documentation>Last modification timestamp</xsd:documentation></xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="closed" type="xsd:boolean" use="required">
				<xsd:annotation><xsd:documentation>Current error message</xsd:documentation></xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== iFlowBPM/iFlow/iflow-api/src/test/resources/ProcessData.xml
<?xml version="1.0" encoding="UTF-8"?>
<processdata fid="1" pid="2" spid="3" pnumber="proc2" creator="creator" creationDate="2008-09-16T09:05:20Z" currentUser="user" lastUpdate="2008-09-19T09:05:20Z" closed="0" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns="http://www.iflow.pt/ProcessData"
   xsi:schemaLocation="http://www.iflow.pt/ProcessData processdata.xsd"
   >
            <e><![CDATA[Um erro qualquer & outra coisa...]]></e>
            <a n="aText">Some text</a>
            <a n="aInteger">100000000000006200000</a>
            <a n="aFloat">100000000000000330000</a>
            <a n="aDate">31072008140753000</a>
            <l n="lText" s="4">
                <i p="0">Text value 0</i>
                <i p="2">Text value 2</i>
            </l>
            <l n="lInteger" s="4">
                <i p="0">100000000000006200000</i>
                <i p="2">000000000000003200000</i>
            </l>
            <l n="lFloat" s="4">
                <i p="0">000000000000012234000</i>
                <i p="2">100000000000012234000</i>
            </l>
            <l n="lDate" s="4">
                <i p="0">21052008140753000</i>
                <i p="2">21062008140753000</i>
            </l>
</processdata>

=== iFlowBPM/iFlow/iflow-api/src/test/resources/ProcessDataSAX.xml
<?xml version="1.0" encoding="UTF-8"?><processdata xmlns="http://www.iflow.pt/ProcessData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.iflow.pt/ProcessData processdata.xsd" fid="1" pid="2" spid="3" pnumber="proc2" creator="creator" creationDate="2008-09-16T09:05:20Z" currentUser="user" lastUpdate="2008-09-19T09:05:20Z" closed="0"><e/><a n="aDate">31072008140753000</a><a n="aFloat">100000000000000330000</a><a n="aInteger">100000000000006200000</a><a n="aText">Helló&lt;&gt;wõrlçad!</a><l n="lDate" s="4"><i p="0">21052008140753000</i><i p="2">21062008140753000</i></l><l n="lFloat" s="4"><i p="0">000000000000012234000</i><i p="2">100000000000012234000</i></l><l n="lInteger" s="4"><i p="0">100000000000006200000</i><i p="2">000000000000003200000</i></l><l n="lText" s="4"><i p="0">Text value 0</i><i p="2">Text value 2</i></l></processdata>
