=== iFlowBPM/iFlow/iflow-editor/schemas/xmllibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.iknow.pt/XmlLibrary"
	xmlns="http://www.iknow.pt/XmlLibrary"
	elementFormDefault="qualified">

  <xsd:annotation >
    <xsd:documentation xml:lang="en">
      Library schema for Flow Editor.
      Copyright 2005 iKnow.
    </xsd:documentation>
  </xsd:annotation>

  <!-- XmlFlow -->
  <xsd:element name="XmlLibrary">
      <xsd:complexType>
          <xsd:sequence>
              <xsd:element name="name"           type="xsd:string"/>
              <xsd:element name="version"        type="xsd:string"/>
              <xsd:element name="author"         type="xsd:string"/>
              <xsd:element name="description"    type="xsd:string"/>
              <xsd:element name="XmlBlock"       type="XmlBlockType"       minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
  </xsd:element>

   <!-- XmlBlockType -->
  <xsd:complexType name="XmlBlockType">
    <xsd:sequence>
      <xsd:element name="class"                type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Nome da classe que implementa o bloco no iFlow. O "package" correcto será acrescentado.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="XmlPort"              type="XmlPortType"   minOccurs="0" maxOccurs="unbounded">
      	<xsd:annotation>
      	  <xsd:documentation>Permite definir um porto de ligação entre blocos.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="XmlAttribute"         type="XmlAttributeType"   minOccurs="0" maxOccurs="unbounded">
      	<xsd:annotation>
      	  <xsd:documentation>Define um atributo do bloco</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="image"                type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Imagem/icon que representa o bloco</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="color"			       type="XmlBlockColor" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Cor da borda do bloco</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="className"            type="xsd:string" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Nome (completo) da classe que permite alterar os atributos do bloco no Editor.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="size"                 type="SizeType" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Não definir!</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="fileName"             type="xsd:string" minOccurs="0">
      	<xsd:annotation>
      	  <xsd:documentation>Não definir!</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="description"          type="xsd:string" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Nome a utilizar na apresentação do bloco. Se não for especificado, usa o valor de class.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="automatic"                 type="BoolType" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>O bloco é automático ou não.
      	   Se o bloco for automático é SEMPRE adicionado ao fluxo e NÃO pode ser REMOVIDO.
      	   Um bloco automático não está disponível na biblioteca para ser adicionado ao fluxo.
      	   Aceita os seguintes valores: yes, no, true, false.
      	   </xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <!-- XmlPortType -->
  <xsd:complexType name="XmlPortType">
    <xsd:sequence>
      <xsd:element name="name"                 type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Nome do porto. Tem que existir um porto com o mesmo nome no bloco do iFlow.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="description"          type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Descrição do porto</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="in_out"               type="InOutType">
      	<xsd:annotation>
      	  <xsd:documentation>Tipo de bloco. Pode ser entrada (in) ou saída (out).</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="position"             type="XmlPositionType"   minOccurs="0" maxOccurs="1">
      	<xsd:annotation>
      	  <xsd:documentation>Posição relativa do porto em relação ao bloco.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <!-- XmlAttributeType -->
  <xsd:complexType name="XmlAttributeType">
    <xsd:sequence>
      <xsd:element name="name"                type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Nome do atributo</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="description"         type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Descrição do atributo</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="value"               type="xsd:string" nillable="true" minOccurs="0">
      	<xsd:annotation>
      	  <xsd:documentation>Valor por omissão a atribuir ao atributo</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="valueType"			  type="xsd:string"   minOccurs="0" maxOccurs="unbounded">
      	<xsd:annotation>
      	  <xsd:documentation>Tipo de dados</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <!-- XmlPositionType -->
  <xsd:complexType name="XmlPositionType">
    <xsd:sequence>
      <xsd:element name="x"                   type="xsd:integer"/>
      <xsd:element name="y"                   type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- XmlBlockColor -->
  <xsd:complexType name="XmlBlockColor">
  	<xsd:attribute name="r" type="RGBType" use="required" />
  	<xsd:attribute name="g" type="RGBType" use="required"/>
  	<xsd:attribute name="b" type="RGBType" use="required"/>
  	<xsd:attribute name="a" type="RGBType" use="required"/>
  </xsd:complexType>

  <!-- SizeType -->
  <xsd:complexType name="SizeType">
    <xsd:sequence>
      <xsd:element name="x"                   type="xsd:integer"/>
      <xsd:element name="y"                   type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- InOut type -->
  <xsd:simpleType name="InOutType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="in"/>
      <xsd:enumeration value="out"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!-- Bool type -->
  <xsd:simpleType name="BoolType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="yes"/>
      <xsd:enumeration value="no"/>
      <xsd:enumeration value="true"/>
      <xsd:enumeration value="false"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="RGBType">
  	<xsd:restriction base="xsd:integer">
  		<xsd:minInclusive value="0" />
  		<xsd:maxInclusive value="255" />
  	</xsd:restriction>
  </xsd:simpleType>


</xsd:schema>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P19068.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>P19068</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>P19068</description>
	<i18nName>library.P19068.name</i18nName>
	<i18nDescription>library.P19068.description</i18nDescription>

	<XmlBlock>
		<class>BlockP19068SyncUsersAndProfiles</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputDocument</name>
			<description>Input file</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>outputErrorDocument</name>
			<description>Output error file</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>ImportIndicioFile</description>
		<i18n>ImportIndicioFile</i18n>
	</XmlBlock>
	
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P19068GetMapsSnapshot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>GetMapsSnapshot</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>GetMapsSnapshot</description>
	<i18nName>library.getmapssnapshot.name</i18nName>
	<i18nDescription>library.getmapssnapshot.description</i18nDescription>

	<XmlBlock>
		<class>BlockGetMapsSnapshot</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
            <name>portEmpty</name>
            <description>portEmpty</description>
            <in_out>out</in_out>
            <position>
                <x>48</x>
                <y>60</y>
            </position>
        </XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputMorada</name>
			<description>Input morada</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>apiKey</name>
			<description>Input API key</description>
			<value />
		</XmlAttribute>
		 <XmlAttribute>
            <name>Document</name>
            <description>Holder documento</description>
            <value />
        </XmlAttribute>
		<image>bpmn_task.png</image>
		<description>BlockGetMapsSnapshot</description>
		<i18n>BlockGetMapsSnapshot</i18n>
	</XmlBlock>
	
	
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/UDW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>UDW</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>UDW</description>
	<i18nName>library.udw.name</i18nName>
	<i18nDescription>library.udw.description</i18nDescription>
	
	<XmlBlock>
		<class>BlockEPublicaRH</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputFlag</name>
			<description>Integration/Validation</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>ePublicaRH</description>
		<i18n>library.udw.block.ePublicaRH</i18n>
	</XmlBlock>
	
	
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries/basica.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>Basic</name>
	<version>1.0</version>
	<author>iKnow</author>
	<description>Basic</description>
	<i18nName>library.basic.name</i18nName>
	<i18nDescription>library.basic.description</i18nDescription>
	<XmlBlock>
		<class>BlockStart</class>
		<XmlPort>
			<name>portOut</name>
			<description>Start</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<image>start.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosStart</className>
		<description>Start</description>
		<i18n>library.basic.block.start</i18n>
		<automatic>true</automatic>
	</XmlBlock>
	<XmlBlock>
		<class>BlockEnd</class>
		<XmlPort>
			<name>portIn</name>
			<description>End</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>UserMessage</name>
			<description>User Message</description>
			<value></value>
		</XmlAttribute>
		<image>stop.png</image>
		<description>End</description>
		<i18n>library.basic.block.end</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockFormulario</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFront</name>
			<description>portFront</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portEvent</name>
			<description>portEvent</description>
			<in_out>out</in_out>
			<position>
				<x>25</x>
				<y>70</y>
			</position>
		</XmlPort>
		<image>formulario.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosJSP</className>
		<description>Form</description>
		<i18n>library.basic.block.form</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockCopia</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOut</name>
			<description>portOut</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<image>copia.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosCopia</className>
		<description>Assignment</description>
		<i18n>library.basic.block.copy</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockCondicao</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrue</name>
			<description>portTrue</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>10</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFalse</name>
			<description>portFalse</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>40</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>condition</name>
			<description>Condition</description>
			<value />
		</XmlAttribute>
		<image>condicao.png</image>
		<description>Condition</description>
		<i18n>library.basic.block.condition</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockMultiCondition</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC1</name>
			<description>portTrueC1</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>5</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC2</name>
			<description>portTrueC2</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC3</name>
			<description>portTrueC3</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC4</name>
			<description>portTrueC1</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>35</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFalse</name>
			<description>portFalse</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>50</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>condition0</name>
			<description>Se</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>condition1</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>condition2</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>condition3</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<image>condicao.png</image>
		<description>MultiCondition</description>
		<i18n>library.basic.block.multi_condition</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockValidacoes</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOutError</name>
			<description>portOutError</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>40</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOutOk</name>
			<description>portOutOk</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>10</y>
			</position>
		</XmlPort>
		<image>validacoes.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosValidacoes</className>
		<description>Validation</description>
		<i18n>library.basic.block.validation</i18n>
	</XmlBlock>
	<!-- disabled for now XmlBlock>
		<class>BlockWebForm</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFront</name>
			<description>portFront</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portEvent</name>
			<description>portEvent</description>
			<in_out>out</in_out>
			<position>
				<x>25</x>
				<y>55</y>
			</position>
		</XmlPort>
		<image>formulario.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosWebForm</className>
		<description>Web Form (beta)</description>
		<i18n>library.basic.block.webform</i18n>
	</XmlBlock -->
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/comments.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Nesta biblioteca encontram-se blocos relativos a comentários nos fluxos (Comment, todo, etc) -->
<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>Comments</name>
	<version>1.0</version>
	<author>iKnow</author>
	<description>Comment Blocks</description>
	<i18nName>library.comments.name</i18nName>
	<i18nDescription>library.comments.description</i18nDescription>
	<XmlBlock>
		<class>BlockComment</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>30</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOut</name>
			<description>portOut</description>
			<in_out>out</in_out>
			<position>
				<x>105</x>
				<y>30</y>
			</position>
		</XmlPort>
		<image>bpmn_comment.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosBeanShell</className>
		<description>Comment</description>
		<i18n>library.comments.block.comment</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockToDo</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>30</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOut</name>
			<description>portOut</description>
			<in_out>out</in_out>
			<position>
				<x>105</x>
				<y>30</y>
			</position>
		</XmlPort>
		<image>bpmn_todo.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosBeanShell</className>
		<description>To Do</description>
		<i18n>library.comments.block.todo</i18n>
	</XmlBlock>
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries/reporting.xml
<?xml version="1.0" encoding="UTF-8"?>
<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>Reporting</name>
	<version>1.0</version>
	<author>iKnow</author>
	<description>Reporting</description>
	<i18nName>library.report.name</i18nName>
	<i18nDescription>library.report.description</i18nDescription>
	<XmlBlock>
		<class>BlockReport</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOut</name>
			<description>portOut</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>Report</name>
			<description>Report code</description>
			<value></value>
		</XmlAttribute>			
		<XmlAttribute>
			<name>TTL</name>
			<description>Expected time to completion</description>
			<value>days=0;hours=0;mins=0;secs=0</value>
		</XmlAttribute>
		<XmlAttribute>
			<name>Deadline</name>
			<description>Deadline</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>Insert</name>
			<description>Enter multiple entries for the same code</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>StopBetween</name>
			<description>Stop reporting between blocks</description>
			<value></value>
		</XmlAttribute>
		<image>report.png</image>
		<description>Report</description>
		<i18n>library.report.block.report</i18n>
	</XmlBlock>
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P19068ReverseGeocodeDecimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>ReverseGeocodeDecimal</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>ReverseGeocodeDecimal</description>
	<i18nName>library.reversegeocodedecimal.name</i18nName>
	<i18nDescription>library.reversegeocodedecimal.description</i18nDescription>

	<XmlBlock>
		<class>BlockReverseGeocodeDecimal</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputLatitudeDecimal</name>
			<description>Input latitude</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>inputLongitudeDecimal</name>
			<description>Input longitude</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>outputMoradas</name>
			<description>Output lista de moradas</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>BlockReverseGeocodeDecimal</description>
		<i18n>library.reversegeocodedecimal.block.reverseGeocodeDecimal</i18n>
	</XmlBlock>
	
	
</XmlLibrary>
