=== iFlowBPM/iFlow/iflow-editor/schemas/xmllibrary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.iknow.pt/XmlLibrary"
	xmlns="http://www.iknow.pt/XmlLibrary"
	elementFormDefault="qualified">

  <xsd:annotation >
    <xsd:documentation xml:lang="en">
      Library schema for Flow Editor.
      Copyright 2005 iKnow.
    </xsd:documentation>
  </xsd:annotation>

  <!-- XmlFlow -->
  <xsd:element name="XmlLibrary">
      <xsd:complexType>
          <xsd:sequence>
              <xsd:element name="name"           type="xsd:string"/>
              <xsd:element name="version"        type="xsd:string"/>
              <xsd:element name="author"         type="xsd:string"/>
              <xsd:element name="description"    type="xsd:string"/>
              <xsd:element name="XmlBlock"       type="XmlBlockType"       minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
  </xsd:element>

   <!-- XmlBlockType -->
  <xsd:complexType name="XmlBlockType">
    <xsd:sequence>
      <xsd:element name="class"                type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Nome da classe que implementa o bloco no iFlow. O "package" correcto será acrescentado.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="XmlPort"              type="XmlPortType"   minOccurs="0" maxOccurs="unbounded">
      	<xsd:annotation>
      	  <xsd:documentation>Permite definir um porto de ligação entre blocos.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="XmlAttribute"         type="XmlAttributeType"   minOccurs="0" maxOccurs="unbounded">
      	<xsd:annotation>
      	  <xsd:documentation>Define um atributo do bloco</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="image"                type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Imagem/icon que representa o bloco</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="color"			       type="XmlBlockColor" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Cor da borda do bloco</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="className"            type="xsd:string" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Nome (completo) da classe que permite alterar os atributos do bloco no Editor.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="size"                 type="SizeType" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Não definir!</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="fileName"             type="xsd:string" minOccurs="0">
      	<xsd:annotation>
      	  <xsd:documentation>Não definir!</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="description"          type="xsd:string" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>Nome a utilizar na apresentação do bloco. Se não for especificado, usa o valor de class.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="automatic"                 type="BoolType" minOccurs="0" >
      	<xsd:annotation>
      	  <xsd:documentation>O bloco é automático ou não.
      	   Se o bloco for automático é SEMPRE adicionado ao fluxo e NÃO pode ser REMOVIDO.
      	   Um bloco automático não está disponível na biblioteca para ser adicionado ao fluxo.
      	   Aceita os seguintes valores: yes, no, true, false.
      	   </xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <!-- XmlPortType -->
  <xsd:complexType name="XmlPortType">
    <xsd:sequence>
      <xsd:element name="name"                 type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Nome do porto. Tem que existir um porto com o mesmo nome no bloco do iFlow.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="description"          type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Descrição do porto</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="in_out"               type="InOutType">
      	<xsd:annotation>
      	  <xsd:documentation>Tipo de bloco. Pode ser entrada (in) ou saída (out).</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="position"             type="XmlPositionType"   minOccurs="0" maxOccurs="1">
      	<xsd:annotation>
      	  <xsd:documentation>Posição relativa do porto em relação ao bloco.</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <!-- XmlAttributeType -->
  <xsd:complexType name="XmlAttributeType">
    <xsd:sequence>
      <xsd:element name="name"                type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Nome do atributo</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="description"         type="xsd:string">
      	<xsd:annotation>
      	  <xsd:documentation>Descrição do atributo</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="value"               type="xsd:string" nillable="true" minOccurs="0">
      	<xsd:annotation>
      	  <xsd:documentation>Valor por omissão a atribuir ao atributo</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
      <xsd:element name="valueType"			  type="xsd:string"   minOccurs="0" maxOccurs="unbounded">
      	<xsd:annotation>
      	  <xsd:documentation>Tipo de dados</xsd:documentation>
      	</xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>


  <!-- XmlPositionType -->
  <xsd:complexType name="XmlPositionType">
    <xsd:sequence>
      <xsd:element name="x"                   type="xsd:integer"/>
      <xsd:element name="y"                   type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- XmlBlockColor -->
  <xsd:complexType name="XmlBlockColor">
  	<xsd:attribute name="r" type="RGBType" use="required" />
  	<xsd:attribute name="g" type="RGBType" use="required"/>
  	<xsd:attribute name="b" type="RGBType" use="required"/>
  	<xsd:attribute name="a" type="RGBType" use="required"/>
  </xsd:complexType>

  <!-- SizeType -->
  <xsd:complexType name="SizeType">
    <xsd:sequence>
      <xsd:element name="x"                   type="xsd:integer"/>
      <xsd:element name="y"                   type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- InOut type -->
  <xsd:simpleType name="InOutType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="in"/>
      <xsd:enumeration value="out"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!-- Bool type -->
  <xsd:simpleType name="BoolType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="yes"/>
      <xsd:enumeration value="no"/>
      <xsd:enumeration value="true"/>
      <xsd:enumeration value="false"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="RGBType">
  	<xsd:restriction base="xsd:integer">
  		<xsd:minInclusive value="0" />
  		<xsd:maxInclusive value="255" />
  	</xsd:restriction>
  </xsd:simpleType>


</xsd:schema>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P19068Geocode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>Geocode</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>Geocode</description>
	<i18nName>library.geocode.name</i18nName>
	<i18nDescription>library.geocode.description</i18nDescription>

	<XmlBlock>
		<class>BlockGeocode</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputMorada</name>
			<description>Input morada</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>outputCoordenadas</name>
			<description>Output lista de coordenadas</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>BlockGeocode</description>
		<i18n>library.geocode.block.geocode</i18n>
	</XmlBlock>
	
	
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-editor/libraries/basica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>Básica</name>
	<version>1.0</version>
	<author>iKnow</author>
	<description>Básica</description>
	<XmlBlock>
		<class>BlockStart</class>
		<XmlPort>
			<name>portOut</name>
			<description>Start</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<image>start.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosStart</className>
		<description>Início</description>
		<automatic>true</automatic>
	</XmlBlock>
	<XmlBlock>
		<class>BlockEnd</class>
		<XmlPort>
			<name>portIn</name>
			<description>End</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>UserMessage</name>
			<description>User Message</description>
			<value></value>
		</XmlAttribute>
		<image>stop.png</image>
		<description>Fim</description>
	</XmlBlock>
	<XmlBlock>
		<class>BlockFormulario</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFront</name>
			<description>portFront</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portEvent</name>
			<description>portEvent</description>
			<in_out>out</in_out>
			<position>
				<x>25</x>
				<y>55</y>
			</position>
		</XmlPort>
		<image>formulario.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosJSP</className>
		<description>Formulário</description>
	</XmlBlock>
	<XmlBlock>
		<class>BlockCopia</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOut</name>
			<description>portOut</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<image>copia.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosCopia</className>
		<description>Atribuição</description>
	</XmlBlock>
	<XmlBlock>
		<class>BlockCondicao</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrue</name>
			<description>portTrue</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>10</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFalse</name>
			<description>portFalse</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>40</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>condition</name>
			<description>Condição</description>
			<value />
		</XmlAttribute>
		<image>condicao.png</image>
		<description>Condição</description>
	</XmlBlock>
	<XmlBlock>
		<class>BlockMultiCondition</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC1</name>
			<description>portTrueC1</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>5</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC2</name>
			<description>portTrueC2</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC3</name>
			<description>portTrueC3</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC4</name>
			<description>portTrueC1</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>35</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFalse</name>
			<description>portFalse</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>50</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>condition0</name>
			<description>Se</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>condition1</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>condition2</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>condition3</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<image>condicao.png</image>
		<description>MultiCondition</description>
		<i18n>Multiplas Condições</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockValidacoes</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOutError</name>
			<description>portOutError</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>40</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portOutOk</name>
			<description>portOutOk</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>10</y>
			</position>
		</XmlPort>
		<image>validacoes.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosValidacoes</className>
		<description>Validações</description>
  </XmlBlock>
  <!-- disabled for now XmlBlock>
    <class>BlockWebForm</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFront</name>
			<description>portFront</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portEvent</name>
			<description>portEvent</description>
			<in_out>out</in_out>
			<position>
				<x>25</x>
				<y>55</y>
			</position>
		</XmlPort>
    <image>formulario.png</image>
    <className>pt.iknow.floweditor.blocks.AlteraAtributosWebForm</className>
    <description>Formulário Web (beta)</description>
  </XmlBlock-->
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P11662.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>ImportTxtPedidoAvaliacao</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>ImportTxtPedidoAvaliacao</description>
	<i18nName>library.ImportTxtPedidoAvaliacao.name</i18nName>
	<i18nDescription>library.ImportTxtPedidoAvaliacao.description</i18nDescription>
	<XmlBlock>
		<class>BlockP11662ImportTxtPedidoAvaliacao</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
            <name>portEmpty</name>
            <description>portEmpty</description>
            <in_out>out</in_out>
            <position>
                <x>48</x>
                <y>60</y>
            </position>
        </XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputDocument</name>
			<description>Input file</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>inputConfigDocument</name>
			<description>Input config document</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>P11662ImportTxtPedidoAvaliacao</description>
		<i18n>P11662ImportTxtPedidoAvaliacao</i18n>
	</XmlBlock>	
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P17080.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>P17080</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>P17080</description>
	<i18nName>library.P17080.name</i18nName>
	<i18nDescription>library.P17080.description</i18nDescription>

	<XmlBlock>
		<class>BlockImportIndicioFile</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portEmpty</name>
			<description>portEmpty</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>30</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>DatasourceP17080</name>
			<description>Datasource of P17080 schema</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>DatasourcePariPersi</name>
			<description>Datasource of PariPersi schema</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>inputDocument</name>
			<description>Main input file</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>inputCRCDISS</name>
			<description>CRC DISS input file</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>infotrustUsername</name>
			<description>Infotrust webservice username</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>infotrustPassword</name>
			<description>Infotrust webservice password</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>outputDocument</name>
			<description>Result output file</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>ImportIndicioFile</description>
		<i18n>ImportIndicioFile</i18n>
	</XmlBlock>
	
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/basica.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>Basic</name>
	<version>1.0</version>
	<author>iKnow</author>
	<description>Basic</description>
	<i18nName>library.basic.name</i18nName>
	<i18nDescription>library.basic.description</i18nDescription>
	<XmlBlock>
		<class>BlockStart</class>
		<XmlPort>
			<name>portOut</name>
			<description>Start</description>
			<in_out>out</in_out>
			<position>
				<x>50</x>
				<y>25</y>
			</position>
		</XmlPort>
		<image>bpmn_start.png</image>
		<className>pt.iknow.floweditor.blocks.AlteraAtributosStart</className>
		<description>Start</description>
		<i18n>library.basic.block.start</i18n>
		<automatic>true</automatic>
	</XmlBlock>
	<XmlBlock>
		<class>BlockEnd</class>
		<XmlPort>
			<name>portIn</name>
			<description>End</description>
			<in_out>in</in_out>
			<position>
				<x>-2</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>UserMessage</name>
			<description>User Message</description>
			<value></value>
		</XmlAttribute>
		<image>bpmn_end.png</image>
		<description>End</description>
		<i18n>library.basic.block.end</i18n>
	</XmlBlock>
	<XmlBlock>
		<class>BlockEnd</class>
		<XmlPort>
			<name>portIn</name>
			<description>End</description>
			<in_out>in</in_out>
			<position>
				<x>-2</x>
				<y>20</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>UserMessage</name>
			<description>User Message</description>
			<value></value>
		</XmlAttribute>
		<image>bpmn_end_message.png</image>
		<description>End</description>
		<i18n>library.basic.block.end</i18n>
	</XmlBlock>
  <XmlBlock>
    <class>BlockBeanShell</class>
   <XmlPort>
      <name>portIn</name>
      <description>portIn</description>
      <in_out>in</in_out>
      <position>
        <x>-5</x>
        <y>27</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portOut</name>
      <description>portOut</description>
      <in_out>out</in_out>
      <position>
        <x>105</x>
        <y>15</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portError</name>
      <description>portError</description>
      <in_out>out</in_out>
      <position>
        <x>105</x>
        <y>45</y>
      </position>
    </XmlPort>
    <className>pt.iknow.floweditor.blocks.AlteraAtributosBeanShell</className>
    <image>bpmn_task.png</image>
    <description>Task</description>
    <i18n>library.utils.block.bsh</i18n>
  </XmlBlock>
  <XmlBlock>
    <class>BlockSubFlow</class>
    <className>pt.iknow.floweditor.blocks.AlteraAtributosSubFlow</className>
    <XmlPort>
      <name>portIn</name>
      <description>Entrada</description>
      <in_out>in</in_out>
      <position>
        <x>-5</x>
        <y>27</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portSuccess</name>
      <description>Sucesso</description>
      <in_out>out</in_out>
      <position>
        <x>105</x>
        <y>27</y>
      </position>
    </XmlPort>
    <image>bpmn_subprocess.png</image>
    <description>Subprocess</description>
    <i18n>library.utils.block.subflow</i18n>
  </XmlBlock>
	<XmlBlock>
		<class>BlockCondicao</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-2</x>
				<y>30</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrue</name>
			<description>portTrue</description>
			<in_out>out</in_out>
			<position>
				<x>62</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFalse</name>
			<description>portFalse</description>
			<in_out>out</in_out>
			<position>
				<x>62</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>condition</name>
			<description>Condition</description>
			<value />
		</XmlAttribute>
		<image>bpmn_gateway_exclusive.png</image>
		<description>Condition</description>
		<i18n>library.basic.block.condition</i18n>
	</XmlBlock>
		<XmlBlock>
		<class>BlockMultiCondition</class>
		<XmlPort>
			<name>portIn</name>
			<description>portIn</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC1</name>
			<description>portTrueC1</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>5</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC2</name>
			<description>portTrueC2</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC3</name>
			<description>portTrueC3</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portTrueC4</name>
			<description>portTrueC1</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>35</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portFalse</name>
			<description>portFalse</description>
			<in_out>out</in_out>
			<position>
				<x>55</x>
				<y>50</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>condition0</name>
			<description>Se</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>condition1</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>condition2</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<XmlAttribute>
			<name>condition3</name>
			<description>Senão, Verifica Se</description>
			<value></value>
		</XmlAttribute>
		<image>condicao.png</image>
		<description>MultiCondition</description>
		<i18n>library.basic.block.multi_condition</i18n>
	</XmlBlock>
  <XmlBlock>
    <class>BlockBifurcacao</class>
    <XmlPort>
      <name>portIn</name>
      <description>portIn</description>
      <in_out>in</in_out>
      <position>
        <x>-2</x>
        <y>30</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portOut</name>
      <description>portOut</description>
      <in_out>out</in_out>
      <position>
        <x>62</x>
        <y>15</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portSubProc</name>
      <description>portSubProc</description>
      <in_out>out</in_out>
      <position>
        <x>62</x>
        <y>45</y>
      </position>
    </XmlPort>
    <image>bpmn_gateway_paralel.png</image>
    <description>Fork</description>
    <i18n>library.utils.block.fork</i18n>
  </XmlBlock>
  <XmlBlock>
    <class>BlockSincronizacao</class>
    <XmlPort>
      <name>portIn</name>
      <description>portIn</description>
      <in_out>in</in_out>
      <position>
        <x>-2</x>
        <y>15</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portInSubProc</name>
      <description>portInSubProc</description>
      <in_out>in</in_out>
      <position>
        <x>-2</x>
        <y>45</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portOut</name>
      <description>portOut</description>
      <in_out>out</in_out>
      <position>
        <x>62</x>
        <y>30</y>
      </position>
    </XmlPort>
    <className>pt.iknow.floweditor.blocks.AlteraAtributosSincronizacao</className>
    <image>bpmn_gateway_paralel.png</image>
    <description>Join</description>
    <i18n>library.utils.block.sync</i18n>
  </XmlBlock>
  <XmlBlock>
    <class>BlockJuncaoExclusiva</class>
    <XmlPort>
      <name>portIn</name>
      <description>portIn</description>
      <in_out>in</in_out>
      <position>
        <x>-2</x>
        <y>15</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portInSubProc</name>
      <description>portInSubProc</description>
      <in_out>in</in_out>
      <position>
        <x>-2</x>
        <y>45</y>
      </position>
    </XmlPort>
    <XmlPort>
      <name>portOut</name>
      <description>portOut</description>
      <in_out>out</in_out>
      <position>
        <x>62</x>
        <y>30</y>
      </position>
    </XmlPort>
    <image>bpmn_gateway_exclusive.png</image>
    <description>Merge</description>
    <i18n>library.utils.block.merge</i18n>
  </XmlBlock>
</XmlLibrary>

=== iFlowBPM/iFlow/iflow-home/repository_data/1/Libraries_BPMN/P19068ReverseGeocodeDMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by jmv (.) -->

<XmlLibrary xmlns="http://www.iknow.pt/XmlLibrary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.iknow.pt/XmlLibrary ../schemas/xmllibrary.xsd">
	<name>ReverseGeocodeDMS</name>
	<version>1.0</version>
	<author>Uniksystem</author>
	<description>ReverseGeocodeDMS</description>
	<i18nName>library.reversegeocodedms.name</i18nName>
	<i18nDescription>library.reversegeocodedms.description</i18nDescription>

	<XmlBlock>
		<class>BlockReverseGeocodeDMS</class>
		<XmlPort>
			<name>portIn</name>
			<description>Entrada</description>
			<in_out>in</in_out>
			<position>
				<x>-5</x>
				<y>25</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portSuccess</name>
			<description>Sucesso</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>15</y>
			</position>
		</XmlPort>
		<XmlPort>
			<name>portError</name>
			<description>Erro</description>
			<in_out>out</in_out>
			<position>
				<x>102</x>
				<y>45</y>
			</position>
		</XmlPort>
		<XmlAttribute>
			<name>inputLatitudeDMS</name>
			<description>Input latitude</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>inputLongitudeDMS</name>
			<description>Input longitude</description>
			<value />
		</XmlAttribute>
		<XmlAttribute>
			<name>outputMoradas</name>
			<description>Output lista de moradas</description>
			<value />
		</XmlAttribute>
		<image>bpmn_task.png</image>
		<description>BlockReverseGeocodeDMS</description>
		<i18n>BlockReverseGeocodeDMS</i18n>
	</XmlBlock>
	
	
</XmlLibrary>
